/*editor*/
export const SET_EDITOR = "SET_EDITOR"
export const CHANGE_PRESENTATION_NAME = "CHANGE_PRESENTATION_NAME"
export const UNDO = "UNDO"
export const REDO = "REDO"

/*slides*/
export const ADD_EMPTY_SLIDE = "ADD_EMPTY_SLIDE"
export const DELETE_SLIDES = "DELETE_SLIDES"
export const END_MOVE_SLIDES = "END_MOVE_SLIDES"
export const CHOOSE_SLIDES = "CHOOSE_SLIDES"

/*elements*/
    /*main*/
export const CHOOSE_ELEMENTS = "CHOOSE_ELEMENTS"
export const ADD_ELEMENT = "ADD_ELEMENT"
export const DELETE_ELEMENTS = "DELETE_ELEMENTS"
export const ADD_TO_BACKGROUND = "ADD_TO_BACKGROUND"
    /*move*/
export const END_MOVE_ELEMENTS = "END_MOVE_ELEMENTS"
export const CHANGE_TEXT_VALUE = "CHANGE_TEXT_VALUE"
export const CHANGE_POSITION_OF_ELEMENTS = "CHANGE_POSITION_OF_ELEMENTS"
    /*styles*/
export const CHANGE_ELEMENT_FILL_COLOR = "CHANGE_ELEMENT_FILL_COLOR"
export const CHANGE_ELEMENT_BORDER_COLOR = "CHANGE_ELEMENT_BORDER_COLOR"
export const CHANGE_ELEMENT_BORDER_WIDTH = "CHANGE_ELEMENT_BORDER_WIDTH"
        /*styles text*/
export const CHANGE_TEXT_BOLD = "CHANGE_TEXT_BOLD"
export const CHANGE_TEXT_ITALIC = "CHANGE_TEXT_ITALIC"
export const CHANGE_TEXT_UNDERLINE = "CHANGE_TEXT_UNDERLINE"
export const CHANGE_TEXT_FONT = "CHANGE_TEXT_FONT"
export const CHANGE_TEXT_SIZE = "CHANGE_TEXT_SIZE"